Capstone Project
mryeminthu/Capstone-Project pull request #1
Opened 2023-06-28 04:35 UTC by mryeminthu

**Capstone Project**

- Use HTML, CSS and JS 
- Use Flexbox to place elements in the page
- Use GitHub Pages 
- Use objects to store and access data
- Create Home Page and About Page for both mobile version and desktop version
- A private link to the recording: https://www.loom.com/share/55216b5df4b24145bcbdd60ef38da4fa?sid=557b5e4c-0315-46d8-89ac-e0b634737ad1

2023-06-28 07:02 UTC, rica213 requested changes
# 🟡 STATUS: REQUIRED CHANGES ♻️ 

Hi Ye Min, 
My name is Larissa. Your code reviewer 🥰

Great job in implementing your project. Your code is clean 💧 you use semantic HTML 🔝 you use CSS selector 🎨 You are almost done! There are some details that I recommend you to look at. Kindly check my recommendations in the comment section below 👇🏽 
Please do not hesitate to mention me in your comment if anything is not entirely clear 🙏🏽 

<img src="https://media2.giphy.com/media/Hc8PMCBjo9BXa/giphy.gif"/>

Happy coding!

## Highlights

#### 🌵 Use of HTML semantic
#### 🌳 Use of CSS Selectors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and keep rocking 🪨 😁 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 07:02 UTC, rica213 commented on about.html
> +    </section>
- [ ] In the desktop version 💻 of the About page, the section "Partner" is hidden. Kindly remedy that detail 🍡  So that your design will follow the original design 😄

2023-06-28 07:02 UTC, rica213 commented on style.css
> +}
- [ ] Following the original design, the footer:
 - in the mobile version 📱 is **hidden** on the _homepage_ and it has a **white** background on the About page.
 - on the desktop version 💻 has a **white** background on the _homepage_ and a **dark** background on the About page.
 Kindly, consider all the details, even the smallest ones because it will help you to become detail-oriented ❤️ It is a highly sought-after skill for developers 😁

2023-06-28 07:02 UTC, rica213 commented on style.css
> +}
- [ ] Please change the background of the toggle menu to transparent or the same color/pattern as the top section background. In this way, we are consistent with our design 🏜️ It will improve the quality of your design 😍

2023-06-28 07:02 UTC, rica213 commented on index.html
> +      <h1>Famous Classes</h1>
- [ ] It is important to have only one **h1** tag on a page. It should represent the **MAIN HEADING** of the page 🍵 
And having only one **h1** tag on the page will improve the accessibility of your webpage. Kindly, change them to another level of heading h2 to h6, and at least keep one **h1** on your page and no more. 🙏🏽

2023-06-28 07:02 UTC, rica213 commented on about.html
> +      <h1>Daily open hours of Fight Club Gym</h1>
- [ ] Your webpage should have at least one and no more **h1** tags. It will improve accessibility. Note that the **h1** tag carries significant weight in conveying the page's main topic to search engines 🛩️

2023-06-28 16:05 UTC, usorfaitheloho requested changes
Hi @mryeminthu  :thumbsup:  ,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Good use of JavaScript, HTML&CSS best practices ✔️ 
-  Good UI design ✔️
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 16:05 UTC, usorfaitheloho commented on style.css
> +}
You did well in completing some of the changes suggested by the previous reviewer, kudos !!! 👍 , please kindly use the right background color for the footer of your `About page` as it seems to be darker than the design template given to you. it is good to use matching designs with your already existing header for your footer for color matching and consistency while following the design given to show a good attention to detail as a good programmer 😄 

Your design :
![image](https://github.com/mryeminthu/Capstone-Project/assets/20537712/ec21b822-ae8a-439f-bae7-a8f60258fe36)

Behance design :
![image](https://github.com/mryeminthu/Capstone-Project/assets/20537712/d842f1eb-50cd-452e-b4bd-16a220a0aa18)

Kindly note the color difference and make the required changes 👍

2023-06-29 02:21 UTC, Cabraham1 approved these changes
Hi @mryeminthu  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 Good design Implementation ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 02:24 UTC, merged